---
- name: Install base packages
  ansible.builtin.apt:
    name:
      - ufw
      - git
      - neovim
      - btop
      - prometheus-node-exporter
      - zsh
    state: present
    update_cache: true
