---
- name: Ensure adam user exists
  ansible.builtin.user:
    name: adam
    state: present
    shell: /bin/bash
    create_home: true

- name: Ensure adam is in the sudo group
  ansible.builtin.user:
    name: adam
    groups: sudo
    append: true

- name: Set authorized keys from GitHub
  ansible.posix.authorized_key:
    user: adam
    state: present
    key: https://github.com/jaswinford.keys
    exclusive: true
